spring:
  application:
    name: agapi-be-assignment

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/flashsale_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        type:
          preferred_boolean_jdbc_type: TINYINT

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

  # Kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: flashsale-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

# Custom app properties
app:
  jwt:
    secret: flashsale-jwt-secret-key-must-be-at-least-256-bits-long-for-hmac-sha
    access-token-expiry-ms: 900000       # 15 minutes
    refresh-token-expiry-ms: 604800000   # 7 days
  otp:
    length: 6
    expiry-minutes: 5
