apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-backend-java
  labels:
    app: crm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-backend
  template:
    metadata:
      labels:
        app: crm-backend
      # [FIX LỖI 1]: Thêm Annotation để bật AppArmor cho container 'java-app'
      annotations:
        container.apparmor.security.beta.kubernetes.io/java-app: runtime/default
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: java-app
          image: vtb-crm/backend:1.0.0@sha256:1fffb95fd064f53c997da5bb9b2fdb9b14abcad7391fbb7fe42b866358695b16
          ports:
            - containerPort: 8080
          securityContext:
            # [FIX LỖI 3]: Khai báo cấm chạy root trực tiếp ở cấp độ Container
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            # [FIX LỖI 2]: Khai báo bật seccomp profile trực tiếp ở cấp độ Container
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10