apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-backend-java
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: java-app
          image: vtb-crm/backend:latest
          securityContext:
            # Cố tình set quyền cao nhất để kích hoạt Hard Gate của Terrascan
            privileged: true
            runAsUser: 0

  selector: